version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diego-app
    ports:
      - "8080:8080"
    volumes:
      - .:/diego-app
      - /diego-app/node_modules
